### ISSUE TITLE
How do i run this ?

### ISSUE THREAD

**Issue by Teathling** [TheRioMiner/Wallpaper-Engine-Pkg-to-Zip#1]
I've tried building this project with visual studio but the .exe just closes instantly

**Comment by Dartandr** [comment]
I also did not find a release, so I decided to compile this project and after that I simply opened the exe-file in cmd, as it was shown in the README. It worked fine for me

**Comment by Teathling** [comment]
Alright so I ran it into a batch file and I managed to understand how to make it work thanks for the thing RioMiner :D (if anyone needs to know how to make it work reply i'll reply soon)

**Comment by TheRioMiner** [comment]
Of course it close instantly, it designed to run from batch or console. If i make pause like "Console.ReadLine();", I can duplicate consoles every start of batch!
I glad if I helped you :)

**Comment by SirDankenstien** [comment]
> Alright so I ran it into a batch file and I managed to understand how to make it work thanks for the thing RioMiner :D (if anyone needs to know how to make it work reply i'll reply soon)

Yea im new and isk how to run this, can ya help?

**Comment by firecrauter** [comment]
> > Alright so I ran it into a batch file and I managed to understand how to make it work thanks for the thing RioMiner :D (if anyone needs to know how to make it work reply i'll reply soon)
> 
> Yea im new and isk how to run this, can ya help?



download https://cmder.net

open;
Use the CD command to go to the exe directory


example:  cd C:\Users\FireCrauter\Downloads\Wallpaper.Engine.Pkg2Zip

![image](https://user-images.githubusercontent.com/7044466/81237347-cee2d680-8fd5-11ea-9ffa-368cd701646d.png)


Open the exe with:
cmd "Wallpaper Engine Pkg To Zip.exe"

![image](https://user-images.githubusercontent.com/7044466/81237497-2bde8c80-8fd6-11ea-9c8f-1bc55bc999d2.png)

Now I will try to explain how to use it; (first the official tutorial)
---------------------------------------------------------------------------

> Usage: "Wallpaper Engine Pkg To Zip.exe" [-mode] [pkgFile] [zipFile]
> -mode        "-pkg2zip" or "-zip2pkg"
> pkgFile      Wallpaper Engine ".pkg" file path
> zipFile      Archive ".zip" file path
> 
> Example: "Wallpaper Engine Pkg To Zip.exe" -pkg2zip scene.pkg result.zip
> 
> <--->
> The program was created for introductory purposes.
> Files in .pkg files may be copyrighted.
> Source code of this program: https://github.com/TheRioMiner/Wallpaper-Engine-Pkg-to-Zip
> <--->

-------------------------------------------------------------------
You must know the location of the scene.pkg;
![image](https://user-images.githubusercontent.com/7044466/81237652-8d066000-8fd6-11ea-89f4-3b23de27350d.png)


"Wallpaper Engine Pkg To Zip.exe" -pkg2zip "C:\Program Files (x86)\Steam\steamapps\workshop\content\431960\1202569461\scene.pkg" result.zip

In the path, change it to your folder with scene.pkg

> "C:\Program Files (x86)\Steam\steamapps\workshop\content\431960\1202569461\scene.pkg"


Remember to leave the "".
At the end of the path add \scene.pkg

![image](https://user-images.githubusercontent.com/7044466/81237833-ef5f6080-8fd6-11ea-9b66-4457a4058ee2.png)
And already, the result.zip will be created.

**Comment by TheRioMiner** [comment]
Why no one notices **.bat** files?
They are specially created for easy execution.
**Just put "scene.pkg" nearby with exe and run "!pkg2zip.bat".**
