### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by BetterWaifus** [TheRioMiner/Wallpaper-Engine-Pkg-to-Zip#4]
Pkg file: 'scene.pkg' corrupted or unhandled error! - Message:[Exception of type 'System.OutOfMemoryException' was thrown.] pops up when i run it

**Comment by TheRioMiner** [comment]
What size of your scene.pkg?
Seems its very large, or on moment of program running there was not enough memory to handle a file.

**Comment by VoidedStars** [comment]
I have the same issue. Scene is only 5MB, and there is plenty of drive space and free RAM. I'm running Windows 10.

**Comment by TheRioMiner** [comment]
> I have the same issue. Scene is only 5MB, and there is plenty of drive space and free RAM. I'm running Windows 10.

Can you give your scene.pkg, i need to debug and fix it issue.

**Comment by TheRioMiner** [comment]
### **Its a string encoding problem.**
**This issue will be fixed in v2.2**

I suspected that PKGV0002 was different from PKGV0001, but I did not find any differences in my test files, so I left everything as it is, anyway, then everything worked :D
